Network46
studyTF/Study pull request #7
Opened 2020-12-13 06:30 UTC by OhJuhun

1.4~1.6입니다

2020-12-15 16:08 UTC, sbrus1213 approved these changes

2020-12-15 16:34 UTC, sbrus1213 requested changes
```suggestion
파일 위치를 
NetworkStudy/NetworkingClass/ 에서
NetworkStudy/NetworkingClass/1_Overview/ 로 옮기는 건 어떨까요?

1_~
2_~
각 디렉토리가 각 재생목록이면 좋겠다고 생각해서 생성해놨거든유
```

2020-12-16 01:00 UTC, sbrus1213 approved these changes

2020-12-16 12:15 UTC, Ohhong approved these changes
별로네요...

2020-12-16 12:15 UTC, merged